services:
    billeterie.prixdubillet:
            class: Billeterie\BilleterieBundle\BilleteriePrixDuBillet\BilleteriePrixDuBillet

#    billeterie.example:
#        class: Billeterie\BilleterieBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
